name: audioreader
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #loading page spinner
  flutter_spinkit: 5.2.0
  #saving settings
  path_provider: 2.0.15
  #permissions for using external files
  permission_handler: ^10.2.0
  #selecting directories for media source
  file_picker: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

